image:
  name: hashicorp/terraform:1.5.7
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"

before_script:
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 2 hour

apply:
  stage: apply
  script:
    - terraform apply -input=false tfplan
  dependencies:
    - plan
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - when: manual
